#!/usr/bin/env python3
"""Deterministic writer for the Vocci -> Obsidian meeting sync skill.

Owns everything mechanical: folder scaffolding, filenames, frontmatter,
dedup against already-synced Vocci sessions, and regenerating the three
static view notes. It never talks to Vocci and never decides what a
project or priority is -- the calling agent extracts that from the
transcript and hands it in as one JSON payload per session.

Subcommands:
  setup        --vault PATH
  sync-entry   --vault PATH --payload FILE [--force]
  rebuild-views --vault PATH
  status       --vault PATH
"""
import argparse
import json
import re
import sys
from datetime import datetime
from pathlib import Path

FOLDERS = ["Meetings", "Tasks", "Projects", "Views"]
PRIORITIES = ["high", "medium", "low"]
STATUSES = ["open", "in-progress", "done"]
INVALID_CHARS = re.compile(r'[\\/:*?"<>|#^\[\]]')
STATE_DIR = ".vocci-sync"
STATE_FILE = "state.json"
GENERATED_MARK = "*Auto-generated by `vault_sync.py` -- edits here are overwritten on the next sync.*"


def sanitize(name: str, maxlen: int = 80) -> str:
    name = INVALID_CHARS.sub("", name).strip()
    name = re.sub(r"\s+", " ", name)
    return name[:maxlen].rstrip()


def unique_path(dir_path: Path, stem: str, ext: str = ".md") -> Path:
    candidate = dir_path / f"{stem}{ext}"
    if not candidate.exists():
        return candidate
    n = 2
    while (dir_path / f"{stem} ({n}){ext}").exists():
        n += 1
    return dir_path / f"{stem} ({n}){ext}"


def load_state(vault: Path) -> dict:
    p = vault / STATE_DIR / STATE_FILE
    if p.exists():
        return json.loads(p.read_text(encoding="utf-8"))
    return {"sessions": {}}


def save_state(vault: Path, state: dict) -> None:
    d = vault / STATE_DIR
    d.mkdir(parents=True, exist_ok=True)
    (d / STATE_FILE).write_text(json.dumps(state, indent=2, sort_keys=True), encoding="utf-8")


def write_note(path: Path, frontmatter: dict, body: str) -> None:
    lines = ["---"]
    for k, v in frontmatter.items():
        if isinstance(v, list):
            lines.append(f"{k}: [{', '.join(str(x) for x in v)}]")
        elif v is None or v == "":
            lines.append(f"{k}:")
        else:
            lines.append(f'{k}: {v}')
    lines.append("---")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n\n" + body.rstrip() + "\n", encoding="utf-8")


FM_RE = re.compile(r"^---\n(.*?)\n---\n", re.S)


def read_frontmatter(path: Path) -> dict:
    text = path.read_text(encoding="utf-8")
    m = FM_RE.match(text)
    if not m:
        return {}
    fm = {}
    for line in m.group(1).splitlines():
        if ":" not in line:
            continue
        k, _, v = line.partition(":")
        k = k.strip()
        v = v.strip()
        if v.startswith("[") and v.endswith("]"):
            inner = v[1:-1].strip()
            fm[k] = [x.strip() for x in inner.split(",") if x.strip()] if inner else []
        elif v.startswith('"') and v.endswith('"') and len(v) >= 2:
            fm[k] = v[1:-1]
        else:
            fm[k] = v
    return fm


def cmd_setup(args):
    vault = Path(args.vault)
    if not vault.is_dir():
        sys.exit(f"error: vault path does not exist or is not a directory: {vault}")
    for folder in FOLDERS:
        (vault / folder).mkdir(parents=True, exist_ok=True)
    load_state(vault)  # creates nothing yet, but validates we can write there
    save_state(vault, load_state(vault))
    rebuild_views(vault)
    print(json.dumps({"ok": True, "vault": str(vault), "folders": FOLDERS}, indent=2))


def validate_task(t: dict, idx: int):
    if not t.get("description", "").strip():
        sys.exit(f"error: tasks[{idx}] missing non-empty 'description'")
    priority = t.get("priority", "").lower()
    if priority not in PRIORITIES:
        sys.exit(f"error: tasks[{idx}] priority must be one of {PRIORITIES}, got {t.get('priority')!r}")
    status = t.get("status", "open").lower()
    if status not in STATUSES:
        sys.exit(f"error: tasks[{idx}] status must be one of {STATUSES}, got {t.get('status')!r}")


def cmd_sync_entry(args):
    vault = Path(args.vault)
    if not vault.is_dir():
        sys.exit(f"error: vault path does not exist: {vault}")
    payload = json.loads(Path(args.payload).read_text(encoding="utf-8"))

    for field in ("vocci_session_id", "date", "title", "project", "summary"):
        if not str(payload.get(field, "")).strip():
            sys.exit(f"error: payload missing required field '{field}'")
    try:
        datetime.strptime(payload["date"], "%Y-%m-%d")
    except ValueError:
        sys.exit(f"error: date must be YYYY-MM-DD, got {payload['date']!r}")

    tasks = payload.get("tasks", [])
    for i, t in enumerate(tasks):
        validate_task(t, i)

    session_id = payload["vocci_session_id"]
    state = load_state(vault)
    existing = state["sessions"].get(session_id)
    if existing and not args.force:
        print(json.dumps({"ok": False, "skipped": True, "reason": "already synced",
                           "existing": existing}, indent=2))
        return
    if existing and args.force:
        for rel in [existing.get("meeting_note")] + existing.get("task_notes", []):
            if rel:
                p = vault / rel
                if p.exists():
                    p.unlink()

    project_name = sanitize(payload["project"])
    project_path = vault / "Projects" / f"{project_name}.md"
    if not project_path.exists():
        write_note(
            project_path,
            {"type": "project", "status": "active", "tags": ["project"]},
            f"# {project_name}\n\n*No description yet -- fill this in.*\n",
        )

    meeting_stem = sanitize(f"{payload['date']} - {payload['title']}")
    meeting_path = unique_path(vault / "Meetings", meeting_stem)
    meeting_title = meeting_path.stem

    task_notes = []
    task_lines = []
    for t in tasks:
        desc = t["description"].strip()
        priority = t.get("priority", "medium").lower()
        status = t.get("status", "open").lower()
        due = t.get("due", "") or ""
        owner = t.get("owner", "") or "UNKNOWN"
        context = t.get("context", "") or ""

        task_stem = sanitize(f"{payload['date']} - {desc}", maxlen=70)
        task_path = unique_path(vault / "Tasks", task_stem)
        task_title = task_path.stem

        body = (
            f"**Project:** [[{project_name}]]\n"
            f"**From meeting:** [[{meeting_title}]]\n"
            f"**Owner:** {owner}\n"
            f"**Due:** {due or 'none'}\n"
            f"**Priority:** {priority}\n\n"
            f"{desc}\n"
        )
        if context:
            body += f"\n> Context: \"{context}\"\n"

        write_note(
            task_path,
            {
                "type": "task",
                "status": status,
                "priority": priority,
                "project": project_name,
                "due": due,
                "owner": owner,
                "source_meeting": meeting_title,
                "vocci_session_id": session_id,
                "tags": ["task"],
            },
            body,
        )
        task_notes.append(str(task_path.relative_to(vault)))
        task_lines.append(f"- [[{task_title}]] ({priority}, due {due or 'none'}) -- owner: {owner}")

    attendees = payload.get("attendees", [])
    meeting_body = (
        f"**Project:** [[{project_name}]]\n"
        f"**Attendees:** {', '.join(attendees) if attendees else 'unknown'}\n\n"
        f"## Summary\n\n{payload['summary'].strip()}\n\n"
        f"## Action items\n\n" + ("\n".join(task_lines) if task_lines else "*None captured.*") + "\n"
    )
    write_note(
        meeting_path,
        {
            "type": "meeting",
            "date": payload["date"],
            "project": project_name,
            "source": "vocci",
            "vocci_session_id": session_id,
            "attendees": attendees,
            "tags": ["meeting"],
        },
        meeting_body,
    )

    state["sessions"][session_id] = {
        "meeting_note": str(meeting_path.relative_to(vault)),
        "project": project_name,
        "task_notes": task_notes,
        "synced_at": datetime.utcnow().isoformat() + "Z",
    }
    save_state(vault, state)
    rebuild_views(vault)

    print(json.dumps({
        "ok": True,
        "meeting_note": str(meeting_path.relative_to(vault)),
        "project_note": str(project_path.relative_to(vault)),
        "task_notes": task_notes,
    }, indent=2))


def rebuild_views(vault: Path) -> None:
    tasks, projects, meetings = [], [], []
    for p in sorted((vault / "Tasks").glob("*.md")):
        fm = read_frontmatter(p)
        if fm.get("type") == "task":
            fm["_name"] = p.stem
            tasks.append(fm)
    for p in sorted((vault / "Projects").glob("*.md")):
        fm = read_frontmatter(p)
        if fm.get("type") == "project":
            fm["_name"] = p.stem
            projects.append(fm)
    for p in sorted((vault / "Meetings").glob("*.md")):
        fm = read_frontmatter(p)
        if fm.get("type") == "meeting":
            fm["_name"] = p.stem
            meetings.append(fm)

    _write_upcoming_tasks(vault, tasks)
    _write_project_status(vault, tasks, projects, meetings)
    _write_meeting_log(vault, meetings, tasks)


def _sort_key_due(t):
    return (t.get("due") or "9999-99-99")


def _write_upcoming_tasks(vault: Path, tasks):
    lines = ["# Upcoming Tasks", "", GENERATED_MARK, ""]
    open_tasks = [t for t in tasks if t.get("status") != "done"]
    for priority in PRIORITIES:
        bucket = sorted((t for t in open_tasks if t.get("priority") == priority), key=_sort_key_due)
        lines.append(f"## {priority.capitalize()} priority ({len(bucket)})")
        lines.append("")
        if bucket:
            lines.append("| Task | Project | Due | Owner | Status | Meeting |")
            lines.append("|---|---|---|---|---|---|")
            for t in bucket:
                lines.append(
                    f"| [[{t['_name']}]] | [[{t.get('project','')}]] | {t.get('due') or 'none'} "
                    f"| {t.get('owner','UNKNOWN')} | {t.get('status','open')} | [[{t.get('source_meeting','')}]] |"
                )
        else:
            lines.append("*None.*")
        lines.append("")
    (vault / "Views" / "Upcoming Tasks.md").write_text("\n".join(lines) + "\n", encoding="utf-8")


def _write_project_status(vault: Path, tasks, projects, meetings):
    lines = ["# Project Status", "", GENERATED_MARK, "", "| Project | Status | Open Tasks | High Priority Open | Meetings | Last Meeting |", "|---|---|---|---|---|---|"]
    known_names = {p["_name"] for p in projects}
    for name in sorted(known_names | {t.get("project", "") for t in tasks} | {m.get("project", "") for m in meetings}):
        if not name:
            continue
        proj_fm = next((p for p in projects if p["_name"] == name), {})
        proj_tasks = [t for t in tasks if t.get("project") == name]
        open_tasks = [t for t in proj_tasks if t.get("status") != "done"]
        high_open = [t for t in open_tasks if t.get("priority") == "high"]
        proj_meetings = sorted((m for m in meetings if m.get("project") == name), key=lambda m: m.get("date", ""))
        last_meeting = proj_meetings[-1]["date"] if proj_meetings else "none"
        status = proj_fm.get("status", "unknown")
        lines.append(
            f"| [[{name}]] | {status} | {len(open_tasks)} | {len(high_open)} | {len(proj_meetings)} | {last_meeting} |"
        )
    (vault / "Views" / "Project Status.md").write_text("\n".join(lines) + "\n", encoding="utf-8")


def _write_meeting_log(vault: Path, meetings, tasks):
    lines = ["# Meeting Log", "", GENERATED_MARK, "", "| Date | Meeting | Project | Attendees | Tasks Created |", "|---|---|---|---|---|"]
    for m in sorted(meetings, key=lambda m: m.get("date", ""), reverse=True):
        n_tasks = len([t for t in tasks if t.get("source_meeting") == m["_name"]])
        attendees = m.get("attendees", [])
        attendees_str = ", ".join(attendees) if isinstance(attendees, list) else str(attendees)
        lines.append(
            f"| {m.get('date','')} | [[{m['_name']}]] | [[{m.get('project','')}]] | {attendees_str or 'unknown'} | {n_tasks} |"
        )
    (vault / "Views" / "Meeting Log.md").write_text("\n".join(lines) + "\n", encoding="utf-8")


def cmd_rebuild_views(args):
    vault = Path(args.vault)
    if not vault.is_dir():
        sys.exit(f"error: vault path does not exist: {vault}")
    rebuild_views(vault)
    print(json.dumps({"ok": True}, indent=2))


def cmd_status(args):
    vault = Path(args.vault)
    if not vault.is_dir():
        sys.exit(f"error: vault path does not exist: {vault}")
    state = load_state(vault)
    print(json.dumps(state, indent=2))


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    sub = ap.add_subparsers(dest="cmd", required=True)

    s = sub.add_parser("setup")
    s.add_argument("--vault", required=True)
    s.set_defaults(func=cmd_setup)

    s = sub.add_parser("sync-entry")
    s.add_argument("--vault", required=True)
    s.add_argument("--payload", required=True)
    s.add_argument("--force", action="store_true")
    s.set_defaults(func=cmd_sync_entry)

    s = sub.add_parser("rebuild-views")
    s.add_argument("--vault", required=True)
    s.set_defaults(func=cmd_rebuild_views)

    s = sub.add_parser("status")
    s.add_argument("--vault", required=True)
    s.set_defaults(func=cmd_status)

    args = ap.parse_args()
    args.func(args)


if __name__ == "__main__":
    main()
